# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-preview:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    # docker:
    #   - image: cimg/base:stable
    working_directory: ~/repo
    executor: node/default
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-pkgs-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --immutable & cd site && yarn install --immutable && cd ../
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: build components
          command: yarn icon && yarn build:es && yarn build:css
      - run:
          name: build site
          command: yarn build:site
      # - run:
      #   name: Upload site-dist Artifact
      #   uses: actions/upload-artifact@v3.1.1
      #   with:
      #     name: site-dist
      #     path: site/dist

      # - name: Download site-dist Artifact
      #   uses: actions/download-artifact@v3.0.1
      #   with:
      #     # Artifact name
      #     name: site-dist
      #     # Destination path
      #     path: dist/
      - attach_workspace:
          at: ~/repo
      - run:
          name: netlify install
          command: yarn add netlify-cli -D
      # - name: get PreviewID
      #   run: |
      #     if ${{ github.event_name == 'pull_request' }}; then
      #       echo "PreviewID=${{ github.event.number }}" >> $GITHUB_ENV
      #     else
      #       echo "PreviewID=main" >> $GITHUB_ENV
      #     fi
      - runs:
          name: netlify deploy
          command: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID  --dir=site/dist --alias=pr-preview-test
        # command: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID  --dir=site/dist --alias=pr-preview-${{ env.PreviewID }}
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-pr-site:
    jobs:
      - deploy-preview
