# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-site:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: install
        run: yarn && cd site && yarn && cd ../

      - name: build components
        run: yarn icon && yarn build:es && yarn build:css

      - name: build site
        run: yarn build:site

      - name: Upload site-dist Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: site-dist
          path: site/dist
  deploy-preview:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Download site-dist Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: site-dist
          # Destination path
          path: dist/

      - name: netlify install
        run: yarn add netlify-cli -D

      - name: get PreviewID
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            echo "PreviewID=${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "PreviewID=main" >> $GITHUB_ENV
          fi

      - name: netlify deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID  --dir=dist --alias=pr-preview-${{ env.PreviewID }}


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-pr-site:
    jobs:
      - build-site
      - deploy-preview