import * as React from 'react';

interface IconProps extends React.SVGAttributes<SVGElement> {
  style?: React.CSSProperties;
  spin?: boolean;
}

export declare const IconArrowDown: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconArrowFall: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconArrowLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconArrowRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconArrowRise: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconArrowUp: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCaretDown: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCaretLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCaretRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCaretUp: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDoubleDown: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDoubleLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDoubleRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDoubleUp: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDownCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDown: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDragArrow: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExpand: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLeftCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMenuFold: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMenuUnfold: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRightCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRotateLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRotateRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconShrink: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSwap: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconToBottom: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconToLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconToRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconToTop: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUpCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUp: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCheckCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCloseCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExclamationCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExclamationPolygonFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconInfoCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMinusCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlusCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQuestionCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCheckCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCheckSquare: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCheck: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconClockCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCloseCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconClose: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExclamationCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExclamation: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconInfoCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconInfo: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMinusCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMinus: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlusCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlus: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQuestionCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQuestion: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconStop: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconHeartFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconStarFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconThumbDownFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconThumbUpFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconAt: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCloudDownload: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCodeBlock: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCodeSquare: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCode: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCustomerService: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDownload: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExport: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEyeInvisible: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEye: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconHeart: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconHistory: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconHome: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconImport: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLaunch: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconList: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMessageBanned: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMessage: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMoreVertical: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMore: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPoweroff: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRefresh: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconReply: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSave: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconScan: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSearch: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSelectAll: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSend: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSettings: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconShareAlt: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconShareExternal: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconShareInternal: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconStar: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSync: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconThumbDown: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconThumbUp: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTranslate: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUpload: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconVoice: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconAlignCenter: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconAlignLeft: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconAlignRight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconAttachment: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBgColors: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBold: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBrush: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCopy: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDelete: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEdit: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEraser: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFilter: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFindReplace: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFontColors: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFormula: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH1: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH2: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH3: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH4: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH5: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH6: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconH7: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconHighlight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconItalic: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLineHeight: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLink: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconObliqueLine: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconOrderedList: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconOriginalSize: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPaste: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQuote: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRedo: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconScissor: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSortAscending: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSortDescending: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSort: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconStrikethrough: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUnderline: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUndo: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUnorderedList: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconZoomIn: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconZoomOut: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMuteFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPauseCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlayArrowFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlayCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSkipNextFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSkipPreviousFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSoundFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBackward: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconForward: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFullscreenExit: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFullscreen: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLiveBroadcast: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMusic: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMute: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPauseCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPause: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlayArrow: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPlayCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRecordStop: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRecord: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSkipNext: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSkipPrevious: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSound: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBytedanceColor: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLarkColor: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTiktokColor: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconXiguaColor: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFaceBookCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFacebookSquareFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconGoogleCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQqCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTwitterCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconWeiboCircleFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconAlipayCircle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCodeSandbox: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCodepen: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFacebook: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconGithub: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconGitlab: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconGoogle: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQqZone: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQq: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTwitter: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconWechat: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconWechatpay: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconWeibo: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconChineseFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEnglishFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFaceFrownFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFaceMehFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFaceSmileFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMoonFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPenFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSunFill: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconApps: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconArchive: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBook: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBranch: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBug: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconBulb: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCalendarClock: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCalendar: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCamera: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCloud: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCommand: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCommon: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCompass: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconCopyright: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDashboard: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDesktop: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDice: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDragDotVertical: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDragDot: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconDriveFile: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEar: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEmail: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconEmpty: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconExperiment: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFileAudio: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFileImage: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFilePdf: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFileVideo: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFile: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFire: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFolderAdd: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFolderDelete: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconFolder: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconGift: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconIdcard: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconImageClose: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconImage: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconInteraction: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLanguage: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLayout: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLoading: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLocation: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLock: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconLoop: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMan: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMenu: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMindMapping: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMobile: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMoon: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconMosaic: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconNav: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconNotificationClose: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconNotification: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPalette: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPen: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPhone: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPrinter: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPublic: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconPushpin: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconQrcode: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRobotAdd: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconRobot: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSafe: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSchedule: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconShake: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSkin: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconStamp: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconStorage: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSubscribeAdd: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSubscribe: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSubscribed: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconSun: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTag: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTags: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconThunderbolt: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTool: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconTrophy: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUnlock: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUserAdd: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUserGroup: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconUser: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconVideoCamera: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconWifi: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
export declare const IconWoman: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<unknown>>
