name: pr_check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn run dependencies
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: run-icon
        run: yarn icon

      - name: build:cjs
        run: yarn build:cjs

      - name: build:es
        run: yarn build:es

      - name: mock-time
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Singapore'
          timezoneMacos: 'Asia/Singapore'
          timezoneWindows: 'Singapore Standard Time'

      - name: test:client
        run: yarn test:client

      - name: test:node
        run: yarn test:node
